-- AntrophAI Supabase invite-token ledger schema
-- Apply this in the Supabase SQL editor or as a migration.

create table if not exists public.invite_tokens (
  id bigint generated by default as identity primary key,
  token_hash text not null,
  token_prefix text not null,
  tester_label text not null,
  grant_id text,
  current_grant_id text,
  claim_count integer not null default 0,
  status text not null default 'unused',
  min_client_build text,
  claimed_client_build text,
  claimed_at timestamptz,
  revoked_at timestamptz,
  expires_at timestamptz,
  last_seen_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint invite_tokens_status_check
    check (status in ('unused', 'claimed', 'revoked', 'expired')),
  constraint invite_tokens_token_hash_check
    check (char_length(token_hash) = 64),
  constraint invite_tokens_token_prefix_check
    check (char_length(token_prefix) between 6 and 12)
);

alter table public.invite_tokens enable row level security;

create unique index if not exists invite_tokens_token_hash_uq
  on public.invite_tokens (token_hash);

create unique index if not exists invite_tokens_grant_id_uq
  on public.invite_tokens (grant_id)
  where grant_id is not null;

create unique index if not exists invite_tokens_current_grant_id_uq
  on public.invite_tokens (current_grant_id)
  where current_grant_id is not null;

create index if not exists invite_tokens_status_idx
  on public.invite_tokens (status);

create index if not exists invite_tokens_claimed_at_idx
  on public.invite_tokens (claimed_at desc nulls last);

create index if not exists invite_tokens_tester_label_idx
  on public.invite_tokens (tester_label);

create or replace function public.set_invite_tokens_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists invite_tokens_updated_at on public.invite_tokens;

create trigger invite_tokens_updated_at
before update on public.invite_tokens
for each row execute function public.set_invite_tokens_updated_at();
